package com.leetcode.snippets.a389findthedifference;

/**
 * Created by hjmao.
 *
 * URL:
 * =====
 * https://leetcode.com/problems/find-the-difference/
 *
 * Desc:
 * =====
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */

public class Solution {
  protected static final boolean SOLUTION_DONE = false;

  public char findTheDifference(String s, String t) {
    return ' ';
  }
}
